site_name: CLLM
site_description: Semantic Natural Language Compressor for LLM.
site_url: https://github.com/YanickJair/cllm

theme:
    name: 'material'
    custom_dir: 'docs'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        primary: 'amber'
        accent: 'deep orange'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'amber'
        accent: 'deep orange'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: YanickJair/cllm
repo_url: https://github.com/YanickJair/cllm
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Components:
        - Transcript Encoder: 'transcript_encoder.md'
        - System Prompt Encoder: 'sys_prompt_encoder.md'
        - Structured Data Encoder: 'sd_encoder.md'
    - Advanced:
        - CLM Configuration: 'advanced/clm_configuration.md'
        - CLM Output: 'advanced/clm_output.md'
        - CLM Dictionary: 'advanced/clm_vocabulary.md'
        - CLM Tokenization: 'advanced/clm_tokenization.md'
    - Community:
        - Third Party Packages: 'third_party_packages.md'
        - Contributing: 'contributing.md'
        - Code of Conduct: 'code_of_conduct.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
    - css/custom.css